# Generated by Django 3.0.3 on 2020-02-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200222_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='added_by',
        ),
    ]
