# Generated by Django 3.0.3 on 2020-02-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200222_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
