# Generated by Django 3.0.3 on 2020-02-23 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200222_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenignFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='NONE', max_length=100)),
                ('sha_256', models.CharField(max_length=100, unique=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MalwareFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='NONE', max_length=100)),
                ('sha_256', models.CharField(max_length=100, unique=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
